# services:
#   - type: web
#     name: twitter-trends
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn app:app
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.9.0
#     buildFilter:
#       paths:
#         - requirements.txt
#         - "**/*.py"
services:
  - type: web
    name: twitter-trends
    env: python
    buildCommand: | chmod +x setup.sh && ./setup.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: true
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
